// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBgBwuhTpQcydD48umkVz43xxHTcVjWVo',
    appId: '1:309999802592:android:b4a25d04190781706c9885',
    messagingSenderId: '309999802592',
    projectId: 'saharan-99797',
    storageBucket: 'saharan-99797.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2a9KpKL4gkcBcH9hR88VyBoRhq2VqM8',
    appId: '1:309999802592:ios:b38bd5f05533d0746c9885',
    messagingSenderId: '309999802592',
    projectId: 'saharan-99797',
    storageBucket: 'saharan-99797.firebasestorage.app',
    androidClientId: '309999802592-pa474nj0rr85o12gbd3nc9m2gesk42o8.apps.googleusercontent.com',
    iosClientId: '309999802592-co1eqg87cm4h0n7et0vac47t41gh1ud2.apps.googleusercontent.com',
    iosBundleId: 'com.example.saharan',
  );
}
